<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>923f2ff7-17d3-45e2-ab3d-1b6bd0e0d460</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paysys.Application\Paysys.Application.csproj" />
    <ProjectReference Include="..\Paysys.Tokenization\Paysys.Tokenization.csproj" />
    <ProjectReference Include="..\Paysys.Infrastructure\Paysys.Infrastructure.csproj" />
    <ProjectReference Include="..\Paysys.Shared\Paysys.Shared.csproj" />
  </ItemGroup>

</Project>
